Bash scripts and exercises

diff --git a/bin/abs b/bin/abs
--- a/bin/abs
+++ b/bin/abs
@@ -24,6 +24,7 @@ Starting on Fedora
 
 The sha-bang
 	#!/bin/bash
+	A two-byte magic number
 
 VARIABLES
 	VAR_NAME=value
@@ -41,5 +42,29 @@ Conditional Statement
 	case "$1" 
 	checking for cmd arguments
 
-Directory Error messages to stderr
+Command line arguments
+
+	E_WRONG_ARGS=85	# Bad Arguments exit code
+	script_parameters="-a -h -m -z"
+#	cmd parameters
+	if [ $# -ne $Number_of_expected_args ]
+	then
+		echo "Usage: `basename $0` $script_parameters"
+#	`basename $0` is the script's filename.
+	exit $E_WRONG_ARGS
+# 	Exit code for bad arguments
+
+
+Direct Error messages to stderr
 	&>2
+
+Quoting Strings
+	single quotes 'STRINGS' # Full quoting
+	double quotes "STRINGS" # Partial quoting
+
+comma separator
+	( - )
+	concatenates two arithmetric values but only the last one is return
+
+continue
+  sch script
diff --git a/bin/cs b/bin/cs
--- a/bin/cs
+++ b/bin/cs
@@ -2,11 +2,14 @@
 
 # variables
 
-LOG_DIR=/var/log/
+LOG_DIR=/var/log
 ROOT_UID=0	# ROOT USER ID
 LINES=60 # Number of lines to clean
 E_XCD=86 # can't change directory
 E_NOTROOT=87 # Non-root exit error
+LOGFILE=sysinfo.log
+ERRLOG=sysinfo.error
+
 # E_WRONGARGS=85 # Non numerical arguments
 
 
@@ -14,12 +17,13 @@ E_NOTROOT=87 # Non-root exit error
 if [ "$UID" -ne "$ROOT_UID" ]
 then 
 	echo "Must be root to run this script."
-	exit $E_NOTROOT
+	exit $E_NOTROOT >&2
 fi
 if [ -n "$1" ]
 	# Test whether command-line argument is present (non-empty).
 then
 	lines=$1
+	echo "clearing $1 lines"
 else
 	lines=$LINES 
 	# Default, if not specified on command-line.
@@ -36,7 +40,7 @@ fi
 # esac
 #
 
-echo "Changing Directory"
+echo "Changing to $LOG_DIR"
 
 cd $LOG_DIR
 
@@ -44,24 +48,31 @@ if [ `pwd` != "$LOG_DIR" ]  # or if [ "PWD" != "$LOG_DIR" ]
 
 then
 	echo "can't change to $LOG_DIR."
-	exit $E_XCD
+	exit $E_XCD >> $ERRLOG 
 fi  # Doublecheck if in right directory before messing with log files
 
+cd /var/log
+
+tail -n $lines messages > mesg.temp # Save last section of message log file.
+mv mesg.temp messages		# rename it as system log file
+
 cat /dev/null > messages
+
+: > sysinfo.log
+
 cat /dev/null > wtmp
+
+##  ': > wtmp' and '> wtmp' have the same effect
 
 echo "Log files cleaned up."
 
-echo "CLEARING TERMINAL"
-clear
-
-echo "SCREEN CLEARED"
-
-# Efficient way of checking directory 
+## Efficient way of checking directory 
 #
 # cd /var/log/ || {
-#	echo "Cannot change to necessary Directory."
-#	exit $E_XCD;
-#
+#	echo "Cannot change to necessary Directory." >&2
+#	exit $E_XCD >> $ERRLOG 
+##
 
-exit
+exit 0
+#  zero return value from the script upon exit indicates a 
+#+ success to the shell
